version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: com.diffplug.gradle.spotless
    versions:
    - 5.10.0
    - 5.10.1
    - 5.10.2
    - 5.11.0
    - 5.11.1
    - 5.12.0
    - 5.12.1
    - 5.9.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha05
    - 7.0.0-alpha06
    - 7.0.0-alpha07
    - 7.0.0-alpha08
    - 7.0.0-alpha09
    - 7.0.0-alpha10
    - 7.0.0-alpha11
    - 7.0.0-alpha12
    - 7.0.0-alpha13
  - dependency-name: androidx.fragment:fragment-ktx
    versions:
    - 1.2.5
    - 1.3.0
    - 1.3.1
    - 1.3.2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.32
  - dependency-name: androidx.navigation:navigation-ui-ktx
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-fragment-ktx
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-runtime-ktx
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-safe-args-gradle-plugin
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: androidx.constraintlayout:constraintlayout
    versions:
    - 2.1.0-alpha2
  - dependency-name: androidx.test:rules
    versions:
    - 1.3.1-alpha03
    - 1.4.0-alpha04
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.2-native-mt
